"""Add date column to DentistAvailability

Revision ID: c0bb672b4c3e
Revises: 
Create Date: 2023-12-08 19:32:49.994487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0bb672b4c3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dentist_availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dentist_availability', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
